name: "Delete Zimagi from AKS cluster"
on:
  workflow_dispatch:
env:
    LOCATION: westus2
    RESOURCE_GROUP_NAME: zimagi-rg
    AKS_CLUSTER_NAME: zimagi-aks
jobs:
  delete_data_api_database:
    name: "Delete postgresql database"
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-helm@v1
      with:
        version: 'v3.4.0'

    - uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.8'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: "Get aks kubeconfig"
      run: az aks get-credentials --name ${AKS_CLUSTER_NAME} --resource-group ${RESOURCE_GROUP_NAME}

    - name: "Delete data helm chart"
      run: |
        helm delete data -n data
        kubectl delete namespace data

  delete_task_queue:
    name: "Delete task queue"
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-helm@v1
      with:
        version: 'v3.4.0'

    - uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.8'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: "Get aks kubeconfig"
      run: az aks get-credentials --name ${AKS_CLUSTER_NAME} --resource-group ${RESOURCE_GROUP_NAME}

    - name: "Delete tasks helm chart"
      run: |
        helm delete tasks -n tasks
        kubectl delete namespace tasks

  delete_zimagi:
    name: "Deploy zimagi"
    runs-on: ubuntu-latest
    steps:      
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.8'

      - uses: azure/setup-helm@v1
        with:
          version: 'v3.4.0'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Get aks kubeconfig"
        run: az aks get-credentials --name ${AKS_CLUSTER_NAME} --resource-group ${RESOURCE_GROUP_NAME}

      - name: "Delete zimagi"
        run: |
          helm delete command-api -n zimagi
          helm delete data-api -n zimagi
          helm delete scheduler -n zimagi
          helm delete worker -n zimagi
          kubectl delete namespace zimagi